app = "robo-pc"
primary_region = "gru"

[build]

[env]
  PLAYWRIGHT_HEADLESS = "true"
  PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH = "/usr/bin/chromium"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
  POLLING_ASMX_MS = "1000"
  MINUTOS_ANTECIPACAO = "3"
  TIMEOUT_VAGAS_MS = "1800000"
  DIAGNOSTICO_MODALIDADE = "presente"
  FORCAR_EXECUCAO = "false"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
